
ALTER TABLE Users
DROP CONSTRAINT PK_Users;

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY(Id);

ALTER TABLE Users
ADD CONSTRAINT UC_Username UNIQUE(Username);

ALTER TABLE Users
ADD CONSTRAINT CK_UsernameLength CHECK(LEN(Username) >= 3);
